# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.signuptitle = QtWidgets.QLabel(Widget)
        self.signuptitle.setGeometry(QtCore.QRect(310, 70, 141, 51))
        self.signuptitle.setObjectName("signuptitle")
        self.layoutWidget = QtWidgets.QWidget(Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 130, 601, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labeluser1 = QtWidgets.QLabel(self.layoutWidget)
        self.labeluser1.setStyleSheet("")
        self.labeluser1.setObjectName("labeluser1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labeluser1)
        self.lineEditusername1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditusername1.setObjectName("lineEditusername1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditusername1)
        self.labelpass1 = QtWidgets.QLabel(self.layoutWidget)
        self.labelpass1.setObjectName("labelpass1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelpass1)
        self.lineEditpassword1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditpassword1.setObjectName("lineEditpassword1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditpassword1)
        self.labelconfrimpass1 = QtWidgets.QLabel(self.layoutWidget)
        self.labelconfrimpass1.setObjectName("labelconfrimpass1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelconfrimpass1)
        self.lineEditconfrimpassword1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditconfrimpassword1.setObjectName("lineEditconfrimpassword1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditconfrimpassword1)
        self.beackbutton = QtWidgets.QPushButton(Widget)
        self.beackbutton.setGeometry(QtCore.QRect(150, 290, 121, 41))
        self.beackbutton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(157, 35, 114);\n"
"font: 12pt \"Segoe UI\";")
        self.beackbutton.setObjectName("beackbutton")
        self.pushButtonsignup1 = QtWidgets.QPushButton(Widget)
        self.pushButtonsignup1.setGeometry(QtCore.QRect(300, 290, 121, 41))
        self.pushButtonsignup1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(157, 35, 114);\n"
"font: 12pt \"Segoe UI\";")
        self.pushButtonsignup1.setObjectName("pushButtonsignup1")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.signuptitle.setText(_translate("Widget", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700; color:#78003c;\">SignUp</span></p></body></html>"))
        self.labeluser1.setText(_translate("Widget", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#9a004f;\">Username</span></p></body></html>"))
        self.labelpass1.setText(_translate("Widget", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#9a004f;\">Password</span></p></body></html>"))
        self.labelconfrimpass1.setText(_translate("Widget", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#9a004f;\">ConfrimPass</span></p></body></html>"))
        self.beackbutton.setToolTip(_translate("Widget", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; color:#ac2562;\">Beack</span></p></body></html>"))
        self.beackbutton.setText(_translate("Widget", "Beack"))
        self.pushButtonsignup1.setToolTip(_translate("Widget", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700; color:#b63077;\">Signup</span></p></body></html>"))
        self.pushButtonsignup1.setWhatsThis(_translate("Widget", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButtonsignup1.setText(_translate("Widget", "Signup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
