# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(657, 483)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 120, 601, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labeluser1 = QtWidgets.QLabel(self.layoutWidget)
        self.labeluser1.setStyleSheet("")
        self.labeluser1.setObjectName("labeluser1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labeluser1)
        self.lineEditusername2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditusername2.setObjectName("lineEditusername2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditusername2)
        self.labelpass1 = QtWidgets.QLabel(self.layoutWidget)
        self.labelpass1.setObjectName("labelpass1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelpass1)
        self.lineEditpassword2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditpassword2.setObjectName("lineEditpassword2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditpassword2)
        self.labelconfrimpass1 = QtWidgets.QLabel(self.layoutWidget)
        self.labelconfrimpass1.setObjectName("labelconfrimpass1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelconfrimpass1)
        self.lineEditconfrimpassword1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditconfrimpassword1.setObjectName("lineEditconfrimpassword1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditconfrimpassword1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.labelconfrimpass = QtWidgets.QLabel(Form)
        self.labelconfrimpass.setGeometry(QtCore.QRect(110, 280, 61, 31))
        self.labelconfrimpass.setObjectName("labelconfrimpass")
        self.lineEditotp = QtWidgets.QLineEdit(Form)
        self.lineEditotp.setGeometry(QtCore.QRect(170, 280, 101, 26))
        self.lineEditotp.setObjectName("lineEditotp")
        self.pushButtonsendotp = QtWidgets.QPushButton(Form)
        self.pushButtonsendotp.setGeometry(QtCore.QRect(290, 280, 93, 29))
        self.pushButtonsendotp.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(61, 64, 255);")
        self.pushButtonsendotp.setObjectName("pushButtonsendotp")
        self.pushButtonSubmmite = QtWidgets.QPushButton(Form)
        self.pushButtonSubmmite.setGeometry(QtCore.QRect(120, 330, 93, 29))
        self.pushButtonSubmmite.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(61, 64, 255);")
        self.pushButtonSubmmite.setObjectName("pushButtonSubmmite")
        self.pushButtonSubmmite_2 = QtWidgets.QPushButton(Form)
        self.pushButtonSubmmite_2.setGeometry(QtCore.QRect(220, 330, 93, 29))
        self.pushButtonSubmmite_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(61, 64, 255);")
        self.pushButtonSubmmite_2.setObjectName("pushButtonSubmmite_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labeluser1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#9a004f;\">Username</span></p></body></html>"))
        self.labelpass1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#9a004f;\">Password</span></p></body></html>"))
        self.labelconfrimpass1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#9a004f;\">ConfrimPass</span></p></body></html>"))
        self.labelconfrimpass.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#b41e73;\">OTP </span><span style=\" font-size:12pt; font-weight:700; color:#b41e73;\">:</span></p></body></html>"))
        self.pushButtonsendotp.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700; color:#ba1f7c;\">Send</span></p></body></html>"))
        self.pushButtonsendotp.setText(_translate("Form", "Send"))
        self.pushButtonSubmmite.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\">submmite</p></body></html>"))
        self.pushButtonSubmmite.setText(_translate("Form", "Submmite"))
        self.pushButtonSubmmite_2.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\">submmite</p></body></html>"))
        self.pushButtonSubmmite_2.setText(_translate("Form", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
